import {
  colorGold,
  colorBlack,
  colorWhite,
  colorGreyDarkest,
  colorGreyDarker,
  colorGreyDark,
  colorGreyLight,
  colorGreyLighter,
  colorGreyLightest,
  colorPrimary,
  colorPrimaryLight,
  colorAction,
  colorActionLight,
  colorSuccess,
  colorDanger,
  colorDangerLight,
  colorOrange,
  colorYellow,
} from '../../styles/colors';

export const brand = [
  {
    id: 'brand-gold',
    name: 'Gold',
    hex: '#BAA082',
    rgb: colorGold,
    variable: '--color-gold',
  },
  {
    id: 'brand-black',
    name: 'Black',
    hex: '#191919',
    rgb: colorBlack,
    variable: '--color-black',
  },
  {
    id: 'brand-white',
    name: 'White',
    hex: '#FFFFFF',
    rgb: colorWhite,
    variable: '--color-white',
  },
];

export const greys = [
  {
    id: 'grey-darkest',
    name: 'Darkest',
    hex: '#232323',
    rgb: colorGreyDarkest,
    variable: '--color-greyDarkest',
  },
  {
    id: 'grey-darker',
    name: 'Darker',
    hex: '#383838',
    rgb: colorGreyDarker,
    variable: '--color-greyDarker',
  },
  {
    id: 'grey-dark',
    name: 'Dark',
    hex: '#5A5A5A',
    rgb: colorGreyDark,
    variable: '--color-greyDark',
  },
  {
    id: 'grey',
    name: 'Grey',
    hex: '#8B8B8B',
    rgb: colorGreyLightest,
    variable: '--color-greyLightest',
  },
  {
    id: 'grey-light',
    name: 'Light',
    hex: '#BEBEBE',
    rgb: colorGreyLight,
    variable: '--color-greyLight',
  },
  {
    id: 'grey-lighter',
    name: 'Lighter',
    hex: '#DDDDDD',
    rgb: colorGreyLighter,
    variable: '--color-greyLighter',
  },
  {
    id: 'grey-lightest',
    name: 'Lightest',
    hex: '#F5F5F5',
    rgb: colorGreyLightest,
    variable: '--color-greyLightest',
  },
];

export const ui = [
  {
    id: 'ui-primary',
    name: 'Primary',
    hex: '#BAA082',
    rgb: colorPrimary,
    variable: '--color-primary',
  },
  {
    id: 'ui-primary-light',
    name: 'Primary Light',
    hex: '#DBBD9A',
    rgb: colorPrimaryLight,
    variable: '--color-primary--light',
  },
  {
    id: 'ui-action',
    name: 'Action',
    hex: '#19679E',
    rgb: colorAction,
    variable: '--color-action',
  },
  {
    id: 'ui-action-light',
    name: 'Action Light',
    hex: '#297DB8',
    rgb: colorActionLight,
    variable: '--color-action--light',
  },
  {
    id: 'ui-success',
    name: 'Success',
    hex: '#48D56C',
    rgb: colorSuccess,
    variable: '--color-success',
  },
  {
    id: 'ui-danger',
    name: 'Danger',
    hex: '#D55444',
    rgb: colorDanger,
    variable: '--color-danger',
  },
  {
    id: 'ui-danger-light',
    name: 'Danger Light',
    hex: '#EC5E4D',
    rgb: colorDangerLight,
    variable: '--color-danger--light',
  },
  {
    id: 'ui-orange',
    name: 'Orange',
    hex: '#EA9B52',
    rgb: colorOrange,
    variable: '--color-orange',
  },
  {
    id: 'ui-yellow',
    name: 'Yellow',
    hex: '#ECB44A',
    rgb: colorYellow,
    variable: '--color-yellow',
  },
];
